# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27c2333d75817682580623784e9b0af4e675d3ae7dd6339f83cce816376576b5bceb87042622dbb267341f388626538575baa48a6456935777d6a30ef8aaf5d

test:
  secret_key_base: 1e9a15e6c93f4d0e538aa576df7d5b598191102aa999c99998fe2ed1c27614ec070721c8e732542bbbe157c408f691833997dec3063978e9b5b85d1278d5f187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
